export const LOG_EVENTS = {
  APP_BOOTSTRAP_STARTED: 'app.bootstrap.started',
  APP_BOOTSTRAP_CONFIG_LOADED: 'app.bootstrap.config_loaded',
  APP_BOOTSTRAP_COMPLETED: 'app.bootstrap.completed',
  APP_BOOTSTRAP_FAILED: 'app.bootstrap.failed',
  CONFIG_LOAD_STARTED: 'config.load.started',
  CONFIG_LOAD_COMPLETED: 'config.load.completed',
  CONFIG_LOAD_FAILED: 'config.load.failed',
  SETTINGS_PERSIST_STARTED: 'settings.persist.started',
  SETTINGS_PERSIST_COMPLETED: 'settings.persist.completed',
  SETTINGS_PERSIST_FAILED: 'settings.persist.failed',
  AUDIO_PLAYBACK_STARTED: 'audio.playback.started',
  AUDIO_PLAYBACK_PAUSED: 'audio.playback.paused',
  AUDIO_PLAYBACK_STOPPED: 'audio.playback.stopped',
  AUDIO_PLAYBACK_FAILED: 'audio.playback.failed',
  AUDIO_FILE_REPLACE_STARTED: 'audio.file.replace.started',
  AUDIO_FILE_REPLACE_COMPLETED: 'audio.file.replace.completed',
  AUDIO_FILE_REPLACE_FAILED: 'audio.file.replace.failed',
  AUDIO_FILE_RESTORE_STARTED: 'audio.file.restore.started',
  AUDIO_FILE_RESTORE_COMPLETED: 'audio.file.restore.completed',
  AUDIO_FILE_RESTORE_FAILED: 'audio.file.restore.failed',
  AUDIO_DOWNLOAD_STARTED: 'audio.download.started',
  AUDIO_DOWNLOAD_FILE_STARTED: 'audio.download.file.started',
  AUDIO_DOWNLOAD_FILE_COMPLETED: 'audio.download.file.completed',
  AUDIO_DOWNLOAD_FILE_FAILED: 'audio.download.file.failed',
  AUDIO_DOWNLOAD_COMPLETED: 'audio.download.completed',
  TRAY_UNAVAILABLE: 'tray.unavailable',
  TRAY_ACTION_STARTED: 'tray.action.started',
  TRAY_ACTION_COMPLETED: 'tray.action.completed',
  WINDOW_CLOSE_REQUESTED: 'window.close.requested',
  WINDOW_SHUTDOWN_STARTED: 'window.shutdown.started',
  WINDOW_SHUTDOWN_COMPLETED: 'window.shutdown.completed',
  WINDOW_SHUTDOWN_FAILED: 'window.shutdown.failed',
  VALIDATION_FAILED: 'validation.failed',
  FATAL_BOOTSTRAP_FAILED: 'fatal.bootstrap_failed',
  FATAL_UNHANDLED_EXCEPTION: 'fatal.unhandled_exception',
} as const;

export type LogEvent = typeof LOG_EVENTS[keyof typeof LOG_EVENTS];
